language: workflow

tools:
  jdk:
    - 1.8.0_91-b14
  maven:
    - 3.3.9

flows:
  master:
  - (on master, name mvn clean install -f runtime/pom.xml && mvn clean deploy ) mvn clean install -f runtime/pom.xml && mvn clean deploy 
  pr:
  - call: master
